import { Reservation } from "./types";

export const START_TIME = 1170; // 19:30
export const TICK_RATE = 1000; // 1 in-game minute = 1 real-world seconds (at 1x)

export const FIRST_NAMES = [
  "James",
  "Mary",
  "Robert",
  "Patricia",
  "John",
  "Jennifer",
  "Michael",
  "Linda",
  "William",
  "Elizabeth",
  "David",
  "Barbara",
  "Richard",
  "Susan",
  "Joseph",
  "Jessica",
  "Thomas",
  "Sarah",
  "Charles",
  "Karen",
  "Christopher",
  "Nancy",
  "Daniel",
  "Lisa",
  "Matthew",
  "Betty",
  "Anthony",
  "Margaret",
  "Mark",
  "Sandra",
  "Donald",
  "Ashley",
  "Steven",
  "Kimberly",
  "Paul",
  "Emily",
  "Andrew",
  "Donna",
  "Joshua",
  "Michelle",
  "Kenneth",
  "Dorothy",
  "Kevin",
  "Carol",
  "Brian",
  "Amanda",
  "George",
  "Melissa",
  "Edward",
  "Deborah",
  "Ronald",
  "Stephanie",
  "Timothy",
  "Rebecca",
  "Jason",
  "Sharon",
  "Jeffrey",
  "Laura",
  "Ryan",
  "Cynthia",
  "Jacob",
  "Kathleen",
  "Gary",
  "Amy",
  "Nicholas",
  "Shirley",
  "Eric",
  "Angela",
  "Jonathan",
  "Helen",
  "Stephen",
  "Anna",
  "Larry",
  "Brenda",
  "Justin",
  "Pamela",
  "Scott",
  "Nicole",
  "Brandon",
  "Emma",
  "Benjamin",
  "Samantha",
  "Samuel",
  "Katherine",
  "Gregory",
  "Christine",
  "Alexander",
  "Debra",
  "Frank",
  "Rachel",
  "Patrick",
  "Carolyn",
  "Raymond",
  "Janet",
  "Jack",
  "Catherine",
  "Dennis",
  "Maria",
  "Jerry",
  "Heather",
  "Tyler",
  "Diane",
  "Aaron",
  "Ruth",
  "Jose",
  "Julie",
  "Adam",
  "Olivia",
  "Nathan",
  "Joyce",
  "Henry",
  "Virginia",
  "Douglas",
  "Victoria",
  "Zachary",
  "Kelly",
  "Peter",
  "Lauren",
  "Kyle",
  "Christina",
  "Walter",
  "Joan",
  "Ethan",
  "Evelyn",
  "Jeremy",
  "Judith",
  "Harold",
  "Megan",
  "Keith",
  "Andrea",
  "Christian",
  "Cheryl",
  "Roger",
  "Hannah",
  "Noah",
  "Jacqueline",
  "Gerald",
  "Martha",
  "Carl",
  "Gloria",
  "Terry",
  "Teresa",
  "Sean",
  "Ann",
  "Arthur",
  "Sara",
  "Austin",
  "Madison",
  "Christian",
  "Frances",
  "Lawrence",
  "Janice",
  "Jesse",
  "Ann",
  "Dylan",
  "Alice",
  "Bryan",
  "Jean",
  "Joe",
  "Doris",
  "Jordan",
  "Alice",
  "Billy",
  "Julia",
  "Bruce",
  "Marie",
  "Albert",
  "Kathryn",
  "Willie",
  "Mildred",
  "Gabriel",
  "Grace",
  "Logan",
  "Beverly",
  "Alan",
  "Denise",
  "Juan",
  "Marilyn",
  "Wayne",
  "Amber",
  "Roy",
  "Danielle",
  "Ralph",
  "Abigail",
  "Randy",
  "Brittany",
  "Eugene",
  "Rose",
  "Vincent",
  "Diana",
  "Russell",
  "Natalie",
  "Louis",
  "Sophia",
  "Philip",
  "Alexis",
  "Bobby",
  "Lori",
  "Johnny",
  "Kayla",
  "Howard",
  "Jane",
];

export const LAST_NAMES = [
  "Smith",
  "Johnson",
  "Williams",
  "Brown",
  "Jones",
  "Garcia",
  "Miller",
  "Davis",
  "Rodriguez",
  "Martinez",
  "Hernandez",
  "Lopez",
  "Gonzalez",
  "Wilson",
  "Anderson",
  "Thomas",
  "Taylor",
  "Moore",
  "Jackson",
  "Martin",
  "Lee",
  "Perez",
  "Thompson",
  "White",
  "Harris",
  "Sanchez",
  "Clark",
  "Ramirez",
  "Lewis",
  "Robinson",
  "Walker",
  "Young",
  "Allen",
  "King",
  "Wright",
  "Scott",
  "Torres",
  "Nguyen",
  "Hill",
  "Flores",
  "Green",
  "Adams",
  "Nelson",
  "Baker",
  "Hall",
  "Rivera",
  "Campbell",
  "Mitchell",
  "Carter",
  "Roberts",
  "Gomez",
  "Phillips",
  "Evans",
  "Turner",
  "Diaz",
  "Parker",
  "Cruz",
  "Edwards",
  "Collins",
  "Reyes",
  "Stewart",
  "Morris",
  "Morales",
  "Murphy",
  "Cook",
  "Rogers",
  "Gutierrez",
  "Ortiz",
  "Morgan",
  "Cooper",
  "Peterson",
  "Bailey",
  "Reed",
  "Kelly",
  "Howard",
  "Ramos",
  "Kim",
  "Cox",
  "Ward",
  "Richardson",
  "Watson",
  "Brooks",
  "Chavez",
  "Wood",
  "James",
  "Bennett",
  "Gray",
  "Mendoza",
  "Ruiz",
  "Hughes",
  "Price",
  "Alvarez",
  "Castillo",
  "Sanders",
  "Patel",
  "Myers",
  "Long",
  "Ross",
  "Foster",
  "Jimenez",
  "Powell",
  "Jenkins",
  "Perry",
  "Russell",
  "Sullivan",
  "Bell",
  "Coleman",
  "Butler",
  "Henderson",
  "Barnes",
  "Gonzales",
  "Fisher",
  "Vasquez",
  "Simmons",
  "Romero",
  "Jordan",
  "Patterson",
  "Alexander",
  "Hamilton",
  "Graham",
  "Reynolds",
  "Griffin",
  "Wallace",
  "Moreno",
  "West",
  "Cole",
  "Hayes",
  "Bryant",
  "Herrera",
  "Gibson",
  "Ellis",
  "Tran",
  "Medina",
  "Aguilar",
  "Cassidy",
  "O'Connor",
  "Bianchini",
  "Rossi",
  "Muller",
  "Schmidt",
  "Lefebvre",
  "Dubois",
  "Moreau",
  "Fournier",
];

export const GRID_SIZE = 4;

/** Solo diner baseline; party of two totals 30 in-game minutes (legacy default). */
export const MEAL_DURATION_BASE_MINUTES = 30;
/** Each extra guest adds this many in-game minutes at the table. */
export const MEAL_DURATION_PER_EXTRA_GUEST_MINUTES = 20;

/** Cells with mealDuration ≤ this value turn amber to signal the table is about to free up. */
export const TABLE_TURNING_SOON_THRESHOLD = 10;

export function mealDurationForPartySize(partySize: number): number {
  const n = Math.max(0, Math.floor(partySize) - 1);
  return (
    MEAL_DURATION_BASE_MINUTES + (n - 1) * MEAL_DURATION_PER_EXTRA_GUEST_MINUTES
  );
}

/** Deliberate first-name + time collisions so players must cross-check last name and time. */
export const INITIAL_RESERVATIONS: Reservation[] = [
  {
    id: "res-1",
    time: 1170,
    firstName: "John",
    lastName: "Smith",
    partySize: 2,
    arrived: false,
    partySeated: false,
  },
  {
    id: "res-2",
    time: 1185,
    firstName: "Mary",
    lastName: "Johnson",
    partySize: 4,
    arrived: false,
    partySeated: false,
  },
  {
    id: "res-3",
    time: 1170,
    firstName: "John",
    lastName: "Williams",
    partySize: 6,
    arrived: false,
    partySeated: false,
  },
  {
    id: "res-4",
    time: 1215,
    firstName: "Patricia",
    lastName: "Brown",
    partySize: 2,
    arrived: false,
    partySeated: false,
  },
  {
    id: "res-5",
    time: 1185,
    firstName: "Mary",
    lastName: "Garcia",
    partySize: 3,
    arrived: false,
    partySeated: false,
  },
  {
    id: "res-6",
    time: 1245,
    firstName: "Linda",
    lastName: "Miller",
    partySize: 5,
    arrived: false,
    partySeated: false,
  },
  {
    id: "res-7",
    time: 1260,
    firstName: "William",
    lastName: "Davis",
    partySize: 2,
    arrived: false,
    partySeated: false,
  },
  {
    id: "res-8",
    time: 1275,
    firstName: "Elizabeth",
    lastName: "Rodriguez",
    partySize: 4,
    arrived: false,
    partySeated: false,
  },
  {
    id: "res-9",
    time: 1245,
    firstName: "Linda",
    lastName: "Martinez",
    partySize: 2,
    arrived: false,
    partySeated: false,
  },
  {
    id: "res-10",
    time: 1305,
    firstName: "Barbara",
    lastName: "Jones",
    partySize: 8,
    arrived: false,
    partySeated: false,
  },
];

export const GREETINGS = [
  "Good evening, I'm here for my table.",
  "Hi, I have a reservation.",
  "Hello, table for tonight?",
  "Hey, checking in for my booking.",
];

export const SCAMMER_GREETINGS = [
  "I definitely have a reservation, I just forgot the time.",
  "My name should be in there, I booked it weeks ago.",
  "I'm a regular here, you must have my name.",
];

export const WALK_IN_GREETINGS = [
  "Do you have any space for a walk-in?",
  "We don't have a booking, but we're hoping for a table.",
  "Any chance you can squeeze us in?",
];
